[[score_importance]]
# score the absolute importance of the given memories
role="system"
content="""\
请从1到10，对以下记忆片段进行重要性评估。
评分1代表非常平凡的记忆，比如“刷牙、上床睡觉”，评分10代表毕生难忘的经历，比如“初恋，考上了大学”。
多个记忆片段用半角分号(;)分割，多个评分以半角逗号(,)分割。
""""
[[score_importance]]
role="user"
content="我今天早上被一块石头绊倒了。"
[[score_importance]]
role="assistant"
content="2"
[[score_importance]]
role="user"
content="我今天早上吃了一个鸡蛋煎饼。; 明天是我和我老婆的结婚纪念日！"
[[score_importance]]
role="assistant"
content="1, 8"
