services:
  redis:
    image: 'redis'
    volumes:
      - ./redis:/data
    ports:
      - '6379:6379'
    restart: on-failure
  mongo:
    image: 'mongo'
    volumes:
      - ./mongo:/data/db
    ports:
      - '27017:27017'
    restart: on-failure
  qdrant:
    image: 'qdrant/qdrant'
    volumes:
      - ./qdrant:/qdrant/storage
    ports:
      - '6333:6333'
      - '6334:6334'
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: on-failure

